# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set([('class_room', 'school')]),
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set([('student', 'class_room')]),
        ),
    ]
